Rework implementation to make use of VideoMaster C++ Wrapper
deltacasttv/overlay-from-live-content pull request #17
Opened 2024-12-20 07:57 UTC by laurent-radoux

2024-12-20 16:40 UTC, Nathoufresh requested changes

2024-12-20 16:40 UTC, Nathoufresh commented on src/main.cpp
> +        if (device_id >= Board::count())
device_id could be negative

2025-01-02 09:36 UTC, laurent-radoux commented on src/main.cpp
> +        if (device_id >= Board::count())
I switched the types to `unsigned int` to ensure that those IDs cannot be interpreted as negative.

2025-01-02 09:46 UTC, Nathoufresh approved these changes, later dismissed

2025-01-02 15:33 UTC, Nathoufresh approved these changes

2025-01-02 15:45 UTC, merged